# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  email-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Email report
        run: |
          echo "Hello, here is the report for today." > report.txt
          mail -s "Report" "